### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by a60814billy** [a60814billy/node-14#1]
node.js test report:

```
/Library/Developer/CommandLineTools/usr/bin/python3 tools/test.py -J --mode=release \
		--skip-tests= \
		default \
		addons js-native-api node-api
=== release test-signal-handler ===
Path: abort/test-signal-handler
assert.js:383
    throw err;
    ^

AssertionError [ERR_ASSERTION]: child.signal = SIGTRAP
    at Object.<anonymous> (/Users/raccoon/Documents/node-v14.16.0/test/abort/test-signal-handler.js:21:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
Command: out/Release/node /Users/raccoon/Documents/node-v14.16.0/test/abort/test-signal-handler.js
=== release test-cpu-prof-default ===
Path: sequential/test-cpu-prof-default
Dispatching message { "id": 1, "method": "Profiler.enable" }
Receive CPU profile message, ending = false
Dispatching message { "id": 2, "method": "Profiler.start" }
Receive CPU profile message, ending = false
Dispatching message { "id": 3, "method": "Profiler.setSamplingInterval", "params": { "interval": 1000 } }
Receive CPU profile message, ending = false
assert.js:105
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

null !== 0

    at Object.<anonymous> (/Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-default.js:33:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: 0,
  operator: 'strictEqual'
}
Command: out/Release/node /Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-default.js
=== release test-cpu-prof-dir-absolute ===
Path: sequential/test-cpu-prof-dir-absolute
Dispatching message { "id": 1, "method": "Profiler.enable" }
Receive CPU profile message, ending = false
Dispatching message { "id": 2, "method": "Profiler.start" }
Receive CPU profile message, ending = false
Dispatching message { "id": 3, "method": "Profiler.setSamplingInterval", "params": { "interval": 50 } }
Receive CPU profile message, ending = false
assert.js:105
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

null !== 0

    at Object.<anonymous> (/Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-dir-absolute.js:40:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: 0,
  operator: 'strictEqual'
}
Command: out/Release/node /Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-dir-absolute.js
=== release test-cpu-prof-dir-and-name ===
Path: sequential/test-cpu-prof-dir-and-name
Dispatching message { "id": 1, "method": "Profiler.enable" }
Receive CPU profile message, ending = false
Dispatching message { "id": 2, "method": "Profiler.start" }
Receive CPU profile message, ending = false
Dispatching message { "id": 3, "method": "Profiler.setSamplingInterval", "params": { "interval": 50 } }
Receive CPU profile message, ending = false
assert.js:105
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

null !== 0

    at Object.<anonymous> (/Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-dir-and-name.js:42:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: 0,
  operator: 'strictEqual'
}
Command: out/Release/node /Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-dir-and-name.js
=== release test-cpu-prof-dir-relative ===
Path: sequential/test-cpu-prof-dir-relative
Dispatching message { "id": 1, "method": "Profiler.enable" }
Receive CPU profile message, ending = false
Dispatching message { "id": 2, "method": "Profiler.start" }
Receive CPU profile message, ending = false
Dispatching message { "id": 3, "method": "Profiler.setSamplingInterval", "params": { "interval": 50 } }
Receive CPU profile message, ending = false
assert.js:105
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

null !== 0

    at Object.<anonymous> (/Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-dir-relative.js:39:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: 0,
  operator: 'strictEqual'
}
Command: out/Release/node /Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-dir-relative.js
=== release test-cpu-prof-dir-worker ===
Path: sequential/test-cpu-prof-dir-worker
Dispatching message { "id": 1, "method": "Profiler.enable" }
Receive CPU profile message, ending = false
Dispatching message { "id": 2, "method": "Profiler.start" }
Receive CPU profile message, ending = false
Dispatching message { "id": 3, "method": "Profiler.setSamplingInterval", "params": { "interval": 50 } }
Receive CPU profile message, ending = false
assert.js:105
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

null !== 0

    at Object.<anonymous> (/Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-dir-worker.js:39:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: 0,
  operator: 'strictEqual'
}
Command: out/Release/node /Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-dir-worker.js
=== release test-cpu-prof-drained ===
Path: sequential/test-cpu-prof-drained
Dispatching message { "id": 1, "method": "Profiler.enable" }
Receive CPU profile message, ending = false
Dispatching message { "id": 2, "method": "Profiler.start" }
Receive CPU profile message, ending = false
Dispatching message { "id": 3, "method": "Profiler.setSamplingInterval", "params": { "interval": 50 } }
Receive CPU profile message, ending = false
assert.js:105
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

null !== 0

    at Object.<anonymous> (/Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-drained.js:36:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: 0,
  operator: 'strictEqual'
}
Command: out/Release/node /Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-drained.js
=== release test-cpu-prof-exit ===
Path: sequential/test-cpu-prof-exit
Dispatching message { "id": 1, "method": "Profiler.enable" }
Receive CPU profile message, ending = false
Dispatching message { "id": 2, "method": "Profiler.start" }
Receive CPU profile message, ending = false
Dispatching message { "id": 3, "method": "Profiler.setSamplingInterval", "params": { "interval": 50 } }
Receive CPU profile message, ending = false
assert.js:105
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

null !== 55

    at Object.<anonymous> (/Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-exit.js:35:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: 55,
  operator: 'strictEqual'
}
Command: out/Release/node /Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-exit.js
=== release test-cpu-prof-kill ===
Path: sequential/test-cpu-prof-kill
Dispatching message { "id": 1, "method": "Profiler.enable" }
Receive CPU profile message, ending = false
Dispatching message { "id": 2, "method": "Profiler.start" }
Receive CPU profile message, ending = false
Dispatching message { "id": 3, "method": "Profiler.setSamplingInterval", "params": { "interval": 50 } }
Receive CPU profile message, ending = false
assert.js:105
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'SIGSEGV'
- 'SIGINT'
      ^
    at Object.<anonymous> (/Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-kill.js:36:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 'SIGSEGV',
  expected: 'SIGINT',
  operator: 'strictEqual'
}
Command: out/Release/node /Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-kill.js
=== release test-cpu-prof-name ===
Path: sequential/test-cpu-prof-name
Dispatching message { "id": 1, "method": "Profiler.enable" }
Receive CPU profile message, ending = false
Dispatching message { "id": 2, "method": "Profiler.start" }
Receive CPU profile message, ending = false
Dispatching message { "id": 3, "method": "Profiler.setSamplingInterval", "params": { "interval": 50 } }
Receive CPU profile message, ending = false
assert.js:105
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

null !== 0

    at Object.<anonymous> (/Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-name.js:40:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: 0,
  operator: 'strictEqual'
}
Command: out/Release/node /Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-name.js
=== release test-cpu-prof-worker-argv ===
Path: sequential/test-cpu-prof-worker-argv
assert.js:105
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

null !== 0

    at Object.<anonymous> (/Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-worker-argv.js:34:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: 0,
  operator: 'strictEqual'
}
Command: out/Release/node /Users/raccoon/Documents/node-v14.16.0/test/sequential/test-cpu-prof-worker-argv.js
=== release test-diagnostic-dir-cpu-prof ===
Path: sequential/test-diagnostic-dir-cpu-prof
Dispatching message { "id": 1, "method": "Profiler.enable" }
Receive CPU profile message, ending = false
Dispatching message { "id": 2, "method": "Profiler.start" }
Receive CPU profile message, ending = false
Dispatching message { "id": 3, "method": "Profiler.setSamplingInterval", "params": { "interval": 50 } }
Receive CPU profile message, ending = false
assert.js:105
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

null !== 0

    at Object.<anonymous> (/Users/raccoon/Documents/node-v14.16.0/test/sequential/test-diagnostic-dir-cpu-prof.js:42:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: 0,
  operator: 'strictEqual'
}
Command: out/Release/node /Users/raccoon/Documents/node-v14.16.0/test/sequential/test-diagnostic-dir-cpu-prof.js
=== release test-inspector-stop-profile-after-done ===
Path: sequential/test-inspector-stop-profile-after-done
[test] Connecting to a child Node process
[test] Testing /json/list
[err] Debugger listening on ws://127.0.0.1:54074/0b34c975-c5b5-48b0-9a6a-b47a92f9c3f8
[err] For help, see: https://nodejs.org/en/docs/inspector
[err]
[err] Debugger attached.
[err]
Mismatched noop function calls. Expected exactly 1, actual 0.
    at Proxy.mustCall (/Users/raccoon/Documents/node-v14.16.0/test/common/index.js:334:10)
    at Object.<anonymous> (/Users/raccoon/Documents/node-v14.16.0/test/sequential/test-inspector-stop-profile-after-done.js:30:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
[err] child process crashed, signal SIGSEGV
Command: out/Release/node /Users/raccoon/Documents/node-v14.16.0/test/sequential/test-inspector-stop-profile-after-done.js
=== release test-worker-prof ===
Path: sequential/test-worker-prof
assert.js:105
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: child exited with signal: {
  status: null,
  signal: 'SIGSEGV',
  output: [ null, '', '' ],
  pid: 52223,
  stdout: '',
  stderr: ''
}
    at Object.<anonymous> (/Users/raccoon/Documents/node-v14.16.0/test/sequential/test-worker-prof.js:58:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: 'SIGSEGV',
  expected: null,
  operator: 'strictEqual'
}
Command: out/Release/node /Users/raccoon/Documents/node-v14.16.0/test/sequential/test-worker-prof.js
[02:04|% 100|+ 3112|-  14]: Done
```

**Comment by a60814billy** [comment]
fixed on 285a217

```
if [ ! -r node -o ! -L node ]; then \
	  ln -fs out/Release/node node; fi
/Library/Developer/CommandLineTools/usr/bin/python3 tools/test.py -J --mode=debug \
		--skip-tests= \
		default \
		addons js-native-api node-api
[04:21|% 100|+ 3126|-   0]: Done
/Library/Developer/CommandLineTools/usr/bin/make tooltest
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
```
